### ISSUE TITLE
Home Page: Create Post Cards as per Hi-Fi mockup

### ISSUE THREAD

**Issue by BenitaWZX** [AdvisorySG/ghost-advisory-theme#134]
Link to the Hi-Fi mockups will be sent in the group. Will also be attached here asap.

**Comment by Soon-Poh-Suan** [comment]
Mockups:

![1](https://user-images.githubusercontent.com/72506857/104396303-5b8e5d00-5585-11eb-9a2a-3d04c95bc835.jpg)
![2](https://user-images.githubusercontent.com/72506857/104396314-5e894d80-5585-11eb-84a0-d046312e23b2.jpg)
![3](https://user-images.githubusercontent.com/72506857/104396315-5f21e400-5585-11eb-9267-6c864aa74192.jpg)
![4](https://user-images.githubusercontent.com/72506857/104396317-5f21e400-5585-11eb-99d2-ced03a87b4fe.jpg)
![5](https://user-images.githubusercontent.com/72506857/104396319-5fba7a80-5585-11eb-9ec3-72005f433c02.jpg)
![6](https://user-images.githubusercontent.com/72506857/104396322-60531100-5585-11eb-844e-270aab747f98.jpg)

**Comment by wei2912** [comment]
Just to clarify, the post cards refer to these:

![image](https://user-images.githubusercontent.com/2070423/105604642-ed416a00-5dd0-11eb-86a0-1d1c8448fce4.png)

**Comment by partysnax** [comment]
@BenitaWZX Hi, I have a couple of questions to clarify regarding the design of the postcards:

- If a post doesn't contain an image, should the space for the image be removed or replaced by whitespace/something else?
![2021-03-22_15h22_51](https://user-images.githubusercontent.com/52738067/111954046-7a2f4800-8b22-11eb-8405-2caab9e45849.png)

- How should images of different dimensions be dealt with? Should they all have the same height for the postcard or is it more important that they take up the entire width of the postcard?

Thanks!

**Comment by wei2912** [comment]
@partysnax The image should be replaced by whitespace, and images of different dimensions should be zoomed in till they take up the entire width & height of the postcard without distorting the aspect ratio. (Any CSS code that can do this "zooming" in will do the trick, it doesn't really matter how it's zoomed in. Ideally all images should be of the correct dimensions, but it's impossible to ensure that CSS-wise without distorting the aspect ratio.)

**Comment by wei2912** [comment]
@partysnax Sflr, I forgot to press the Comment button. The image should be replaced by whitespace, and images of different dimensions should be zoomed in till they take up the entire width & height of the postcard without distorting the aspect ratio. (Any CSS code that can do this "zooming" in will do the trick, it doesn't really matter how it's zoomed in. Ideally all images should be of the correct dimensions, but it's impossible to ensure that CSS-wise without distorting the aspect ratio.)

**Comment by wei2912** [comment]
Closing this PR since we've created an initial version of these cards.
