### ISSUE TITLE
Upcoming Events: Create Event Cards as per Hi-Fi mockup

### ISSUE THREAD

**Issue by Soon-Poh-Suan** [AdvisorySG/ghost-advisory-theme#150]
![photo6296179399329950259](https://user-images.githubusercontent.com/72506857/105598434-34c6f680-5dcf-11eb-8b31-fbd862420849.jpg)
![photo6296179399329950260](https://user-images.githubusercontent.com/72506857/105598487-37c1e700-5dcf-11eb-9409-d0dfef4e2ebd.jpg)
![photo6296179399329950261](https://user-images.githubusercontent.com/72506857/105598499-385a7d80-5dcf-11eb-8cee-7835118020bb.jpg)
![photo6296179399329950262](https://user-images.githubusercontent.com/72506857/105598513-398baa80-5dcf-11eb-809d-c0999d59c3c7.jpg)
![photo6296179399329950263](https://user-images.githubusercontent.com/72506857/105598522-3a244100-5dcf-11eb-80eb-a69e25a9ccff.jpg)
![photo6296179399329950264](https://user-images.githubusercontent.com/72506857/105598529-3a244100-5dcf-11eb-9364-48c5dd0db2ed.jpg)

**Comment by wei2912** [comment]
To clarify, the event cards refer to:

![image](https://user-images.githubusercontent.com/2070423/105604923-00543a00-5dd1-11eb-93c9-2ea24b9bcf84.png)

**Comment by wei2912** [comment]
As discussed in PR above, sample event cards have been created. A new issue will be created to set up an Events system.
