### ISSUE TITLE
Implement GScan validation

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/ghost-advisory-theme#189]
Currently, the Ghost themes are not scanned with [GScan](https://github.com/TryGhost/gscan) which helps to validate Ghost themes and flag out potential issues. A CI workflow should be set up to perform this scanning.

**Comment by bnjmnt4n** [comment]
Seems like this is already run in the CI workflow: https://github.com/AdvisorySG/ghost-advisory-theme/blob/8d43461292458c632c4ed663e5c2872d374f5326/package.json#L15, although it currently only fails on fatal errors.

**Comment by wei2912** [comment]
Hmm, that might be why I didn't notice it.
