### ISSUE TITLE
Stories: Implement dynamic filtering with Ghost Content API

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/ghost-advisory-theme#194]
The current filter feature as of https://github.com/AdvisorySG/ghost-advisory-theme/commit/b1e83d606a6cef233f6eed3286cb3e075c530173 prepares the pages of posts at the start and then hides the posts on each page that do not meet the filter criteria. This is not ideal, as preferably posts should be rearranged across pages such that each page has the max. capacity of posts.

E.g. if say there are originally 3 pages of 5+5+3 posts and filtering is done to reduce this to 3+2+1 posts, then the first two pages should be combined together to get 2 pages of 5+1 posts.

**Comment by bnjmnt4n** [comment]
This is actually probably going to be a very difficult problem to solve, and seems like something better suited to WordPress.

If we were to do this, my recommendation would be to disable pagination by Ghost, load all content in the HTML, and continue with our custom filtering + pagination logic in JavaScript.

**Comment by wei2912** [comment]
Yep, that's what I meant to suggest actually.

**Comment by wei2912** [comment]
Closing in favour of a Load More approach, see my comments on https://github.com/AdvisorySG/ghost-advisory-theme/pull/274.
