### ISSUE TITLE
{{#each}} context unaware bug

### ISSUE THREAD

**Issue by DaDevChia** [AdvisorySG/ghost-advisory-theme#286]
<img width="515" alt="Screenshot 2021-08-13 at 7 13 14 PM" src="https://user-images.githubusercontent.com/88506363/129349770-04421e65-216a-4284-bca7-9dac8a4b7d3a.png">

Replacing {{#each}} with {{#foreach}} fixes the above bug.

**Comment by wei2912** [comment]
As mentioned in https://github.com/AdvisorySG/ghost-advisory-theme/pull/285#discussion_r688860705, this warning can be safely ignored. Our current structure is such that we have two "variants" of Handlebars operating on different `.hbs` files, in an attempt to replace direct DOM manipulation code.

Closing this issue for now; feel free to open another issue if you have any suggestions for replacements to HTML generation.

**Comment by wei2912** [comment]
Actually, I might explore Alpine.js. It's probably sufficient for our purposes and can get rid of having to do webpack + Handlebars integration, which is honestly kinda dirty
