### ISSUE TITLE
Yarn not a dependency

### ISSUE THREAD

**Issue by DaDevChia** [AdvisorySG/ghost-advisory-theme#290]
https://github.com/AdvisorySG/ghost-advisory-theme/blob/65314182c5ad6926d7dba7f00b19ac8900bcb613/.husky/pre-commit#L4
yarn is used despite not being a devDependency in package.json which will result in git issues in environments without yarn installed

Either add yarn as a devDependency or use 
`npx -p prettier -p pretty-quick pretty-quick --staged`
to use npx instead

**Comment by wei2912** [comment]
Thanks for checking, `yarn` isn't supposed to be a dependency. `npx pretty-quick --staged` should be sufficient. Fixed in https://github.com/AdvisorySG/ghost-advisory-theme/commit/9ffe68fb15728d1d3d97d70dd5b228306ebce763.
